---
title: "UtahLake_WatershedLoading"
author: "Kateri Salk"
date: "5/3/2021"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

## Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(viridis)
library(wqTools)
library(sf)
library(cowplot)
library(ggrepel)

theme_set(theme_classic())
options(scipen = 4)
```

## Load Datasets
```{r}
unmonitored_loading <- read.csv("./UnmonitoredWS_Modeling/MapMyWatershed/Compiled_Model_Results/water_quality_load_summary.csv")
unmonitored_hydrology <- read.csv("./UnmonitoredWS_Modeling/MapMyWatershed/Compiled_Model_Results/hydrology.csv")

monitored_loading_annual <- read.csv("./Data/Processed/loading_AllWatersheds_annual.csv")
monitored_loading_monthly <- read.csv("./Data/Processed/loading_AllWatersheds.csv")
dmr_loading_monthly <- read.csv("./Data/Processed/loading_AllWatersheds_dmr.csv")
dmr_loading_annual <- read.csv("./Data/Processed/loading_AllWatersheds_dmr_annual.csv")

jordan_loading_annual <- read.csv("./Data/Processed/loading_Jordan_annual.csv")
jordan_loading_monthly <- read.csv("./Data/Processed/loading_Jordan_monthly.csv")
gw_loading_annual <- read.csv("./Data/Processed/loading_groundwater_annual.csv")
precipevap_hydrology_monthly <- read.csv("./Data/Processed/hydrology_precip_et_monthly.csv")

# watershed spatial data
wshds <- read_sf("./Data/GIS/UL_subwshedsWGS84_v2.shp")
```

## Processing 

### Unmonitored Watershed Data
```{r}

unmonitored_loading$Total.Nitrogen <- as.numeric(gsub(",", "", unmonitored_loading$Total.Nitrogen))
unmonitored_loading$Total.Phosphorus <- as.numeric(gsub(",", "", unmonitored_loading$Total.Phosphorus))
unmonitored_loading$WS_Name <- as.factor(unmonitored_loading$WS_Name)
unmonitored_loading$WS_Name <- gsub("_", " ", unmonitored_loading$WS_Name)
unmonitored_loading$WS_Name <- gsub("   ", " - ", unmonitored_loading$WS_Name)
unmonitored_loading$WS_Name[unmonitored_loading$WS_Name == "Lake Mountain -  Gravel Pit"] <- "Lake Mountain  - Gravel Pit"

unmonitored_loading_annual <- unmonitored_loading %>%
  filter(Sources == "Total Loads (kg)") %>%
  mutate(load.TN.tonyr = Total.Nitrogen/1000, 
         load.TP.tonyr = Total.Phosphorus/1000, 
         Flow.cfs = NA, 
         Flow.acftyr = NA,
         load.TDN.tonyr = NA, 
         load.TDP.tonyr = NA, 
         load.TOC.tonyr = NA,
         load.DOC.tonyr = NA,
         WS_Type = "Unmonitored") %>%
  select(WS_Name, Flow.cfs, load.TN.tonyr, load.TDN.tonyr, load.TP.tonyr,
         Flow.acftyr, load.TDP.tonyr, load.TOC.tonyr, load.DOC.tonyr, WS_Type)
  
unmonitored_hydrology$WS_Name <- as.factor(unmonitored_hydrology$WS_Name)
unmonitored_hydrology$WS_Name <- gsub("_", " ", unmonitored_hydrology$WS_Name)
unmonitored_hydrology$WS_Name <- gsub("   ", " - ", unmonitored_hydrology$WS_Name)
unmonitored_hydrology$WS_Name[unmonitored_hydrology$WS_Name == "Lake Mountain -  Gravel Pit"] <- "Lake Mountain  - Gravel Pit"

wshds_area <- wshds %>%
  select(WS_Name, wsa_sqkm)

unmonitored_hydrology_monthly <- unmonitored_hydrology %>%
  mutate(Month = match(Month, month.abb)) %>%
  drop_na(Month) %>%
  left_join(., wshds_area) %>%
  mutate(Flow.cm = Stream.Flow..cm. + Surface.Runoff..cm. + Point.Src.Flow..cm., 
         Flow.acftmo = Flow.cm * wsa_sqkm * 247.105/30.48) %>%
  select(WS_Name, Month, Flow.cm, Flow.acftmo)

unmonitored_hydrology_monthly_total <- unmonitored_hydrology_monthly %>%
  group_by(Month) %>%
  summarise(Flow.acftmo = sum(Flow.acftmo))

unmonitored_hydrology_annual <- unmonitored_hydrology_monthly %>%
  group_by(WS_Name) %>%
  summarise(Flow.acftyr = sum(Flow.acftmo)) 


```

### Reorder watershed names
```{r}
monitored_loading_monthly$WS_Name <- 
  factor(monitored_loading_monthly$WS_Name, 
         levels = c("Tickville Wash", "Dry Creek - Saratoga", "Lehi Spring Creek", 
                    "American Fork River", "Timp SSD", "Lindon Drain", 
                    "Powell Slough Major", "Provo River", "Mill Race", 
                    "Spring Creek - Springville", "Hobble Creek", 
                    "Dry Creek - Spanish Fork", "Spanish Fork River", 
                    "4000 South Drain Spanish Fork", "Benjamin Slough", "Currant Creek"))

monitored_loading_annual$WS_Name <- 
  factor(monitored_loading_annual$WS_Name, 
         levels = c("Tickville Wash", "Dry Creek - Saratoga", "Lehi Spring Creek", 
                    "American Fork River", "Timp SSD", "Lindon Drain", 
                    "Powell Slough Major", "Provo River", "Mill Race", 
                    "Spring Creek - Springville", "Hobble Creek", 
                    "Dry Creek - Spanish Fork", "Spanish Fork River", 
                    "4000 South Drain Spanish Fork", "Benjamin Slough", "Currant Creek"))

unmonitored_hydrology_monthly$WS_Name <- 
  factor(unmonitored_hydrology_monthly$WS_Name, 
         levels = c("Goshen Valley", "Lake Mountain - Clyde Knoll", "Lake Mountain - White Knoll", 
                    "Lake Mountain - Pfeiffer Canyon", "Lake Mountain - Chaparral Canyon", 
                    "Lake Mountain - Miners Canyon", "Lake Mountain  - Gravel Pit", 
                    "Lake Mountain - Little Cover", "Pelican Point", "Lake Mountain - Limekiln Canyon", 
                    "Lake Mountain - Losee Canyon", "Lake Mountain - Israel Canyon", 
                    "Lehi Drain 1", "Lehi Drain 2", "Lehi Drain 3", "Lehi Drain 4", 
                    "Lehi Drain 5", "Lehi Drain 6", "American Fork 1", "American Fork 2", 
                    "Lindon Wetlands", "Lindon Marina", "Vineyard Drain 7", "Vineyard Drain 6", 
                    "Vineyard Drain 5", "Vineyard Drain 4", "Vineyard Drain 3", "Vineyard Drain 2", 
                    "Vineyard Drain 1", "Powell Slough Minor", "Skipper Bay 2", "Skipper Bay 1", 
                    "Provo River Delta Project", "Provo Airport", "Big Dry Creek", "Provo Bay 8",
                    "Provo Bay 7", "Provo Bay 6", "Provo Bay 5", "Provo Bay 4", "Provo Bay 3",
                    "Provo Bay 2", "Provo Bay 1", "Spanish Fork - 1", "Spranish Fork 2",
                    "West Mountain 1", "West Mountain 6", "West Mountain 2", "West Mountain 7",
                    "West Mountain 3", "West Mountain 10", "West Mountain 4", "West Mountain 8",
                    "West Mountain 9", "West Mountain 5"))



```

### Monitored Watershed Data
```{r}
monitored_loading_monthly <- monitored_loading_monthly %>%
  mutate(WS_Type = case_when(
    WS_Name %in% c("Timp SSD", "Powell Slough Major", "Mill Race", 
                   "Spring Creek - Springville", "Dry Creek - Spanish Fork", 
                   "Benjamin Slough") ~ "WWTP", 
    TRUE ~ "No WWTP"))

monitored_loading_monthly_total <- monitored_loading_monthly %>%
  group_by(Month) %>%
  summarise(Flow.acftmo = sum(Flow.acftmo))

# For Timp SSD, Powell Slough, and Mill Race, use DMR data for loading estimates when available.
# Decided on by the SP 5/20/21
monitored_loading_annual$load.TN.tonyr[monitored_loading_annual$WS_Name == "Timp SSD"] <- 
  dmr_loading_annual$load.TN.tonyr[dmr_loading_annual$WS_Name == "Timp SSD"]
monitored_loading_annual$load.TP.tonyr[monitored_loading_annual$WS_Name == "Timp SSD"] <- 
  dmr_loading_annual$load.TP.tonyr[dmr_loading_annual$WS_Name == "Timp SSD"]
monitored_loading_annual$load.TDP.tonyr[monitored_loading_annual$WS_Name == "Timp SSD"] <- 
  dmr_loading_annual$load.TDP.tonyr[dmr_loading_annual$WS_Name == "Timp SSD"]

monitored_loading_annual$load.TN.tonyr[monitored_loading_annual$WS_Name == "Powell Slough"] <- 
  dmr_loading_annual$load.TN.tonyr[dmr_loading_annual$WS_Name == "Powell Slough"]
monitored_loading_annual$load.TP.tonyr[monitored_loading_annual$WS_Name == "Powell Slough"] <- 
  dmr_loading_annual$load.TP.tonyr[dmr_loading_annual$WS_Name == "Powell Slough"]
monitored_loading_annual$load.TDP.tonyr[monitored_loading_annual$WS_Name == "Powell Slough"] <- 
  dmr_loading_annual$load.TDP.tonyr[dmr_loading_annual$WS_Name == "Powell Slough"]

monitored_loading_annual$load.TN.tonyr[monitored_loading_annual$WS_Name == "Mill Race"] <- 
  dmr_loading_annual$load.TN.tonyr[dmr_loading_annual$WS_Name == "Mill Race"]
monitored_loading_annual$load.TP.tonyr[monitored_loading_annual$WS_Name == "Mill Race"] <- 
  dmr_loading_annual$load.TP.tonyr[dmr_loading_annual$WS_Name == "Mill Race"]
monitored_loading_annual$load.TDP.tonyr[monitored_loading_annual$WS_Name == "Mill Race"] <- 
  dmr_loading_annual$load.TDP.tonyr[dmr_loading_annual$WS_Name == "Mill Race"]

monitored_loading_annual <- monitored_loading_annual %>%
  mutate(WS_Type = case_when(
    WS_Name %in% c("Timp SSD", "Powell Slough Major", "Mill Race", 
                   "Spring Creek - Springville", "Dry Creek - Spanish Fork", 
                   "Benjamin Slough") ~ "WWTP", 
    TRUE ~ "No WWTP"))

```


### Combine annual loading
```{r}
loading_annual <- monitored_loading_annual %>%
  rbind(., unmonitored_loading_annual) %>%
  left_join(., unmonitored_hydrology_annual, by = "WS_Name") %>%
  mutate(Flow.acftyr = case_when(is.na(Flow.acftyr.x) ~ Flow.acftyr.y, 
                                 TRUE ~ Flow.acftyr.x)) %>%
  select(-Flow.acftyr.x, -Flow.acftyr.y) %>%
  select(WS_Name, Flow.cfs, load.TN.tonyr, load.TDN.tonyr, load.TP.tonyr, Flow.acftyr,
         load.TDP.tonyr, load.TOC.tonyr, load.DOC.tonyr, WS_Type)


jordan_loading_annual <- jordan_loading_annual %>%
  mutate(WS_Type = "Jordan River") %>%
  mutate_if(is.numeric, funs(. * -1))

gw_loading_zones <- gw_loading_annual
gw_loading_annual <- gw_loading_zones %>%
  summarise(Flow.acftyr = sum(Flow.acftyr), 
            load.TP.tonyr = sum(load.TP.tonyr), 
            load.TN.tonyr = sum(load.TN.tonyr)) %>%
  mutate(WS_Name = "Groundwater", 
         Flow.cfs = NA, 
         load.TDN.tonyr = NA, 
         load.TDP.tonyr = NA, 
         load.TOC.tonyr = NA, 
         load.DOC.tonyr = NA,
         WS_Type = "Groundwater") %>%
  select(WS_Name, Flow.cfs, load.TN.tonyr, load.TDN.tonyr, load.TP.tonyr, Flow.acftyr,
         load.TDP.tonyr, load.TOC.tonyr, load.DOC.tonyr, WS_Type)

atm_loading_annual <- data.frame(WS_Name = "Atmosphere", 
                                 Flow.cfs = NA, 
                                 load.TN.tonyr = 170, 
                                 load.TDN.tonyr  = 74.8, 
                                 load.TP.tonyr = 5, 
                                 Flow.acftyr = NA,
                                 load.TDP.tonyr = 2.5, 
                                 load.TOC.tonyr = NA, 
                                 load.DOC.tonyr = NA, 
                                 WS_Type = "Atmosphere")
  
loading_annual <- loading_annual %>%
  rbind(., jordan_loading_annual, gw_loading_annual, atm_loading_annual)

loading_annual$WS_Type <- 
  factor(loading_annual$WS_Type, 
         levels = c("WWTP", "No WWTP", "Unmonitored", "Atmosphere", "Groundwater", "Jordan River"))

loading_annual_summary <- loading_annual %>%
  group_by(WS_Type) %>%
  summarise(load.TN.tonyr = sum(load.TN.tonyr), 
            load.TP.tonyr = sum(load.TP.tonyr)) %>%
  mutate(TN.percent = case_when(
    load.TN.tonyr > 0 ~ load.TN.tonyr/sum(load.TN.tonyr[which(load.TN.tonyr>0)])*100, 
    load.TN.tonyr < 0 ~ load.TN.tonyr/sum(load.TN.tonyr[which(load.TN.tonyr>0)])*100), 
    TP.percent = case_when(
    load.TP.tonyr > 0 ~ load.TP.tonyr/sum(load.TP.tonyr[which(load.TP.tonyr>0)])*100, 
    load.TP.tonyr < 0 ~ load.TP.tonyr/sum(load.TP.tonyr[which(load.TP.tonyr>0)])*100)) 

loading_annual_summary$TN.percent <- round(loading_annual_summary$TN.percent, digits = 1)
loading_annual_summary$TP.percent <- round(loading_annual_summary$TP.percent, digits = 1)

loading_annual_summary$TN.percent <- paste(loading_annual_summary$TN.percent, "%")  
loading_annual_summary$TP.percent <- paste(loading_annual_summary$TP.percent, "%")  

```

### Join spatial and loading data
```{r}
wshds_loading <- wshds %>%
  left_join(., loading_annual)
```

## Calculations
### total tributary inflow

```{r}
flow_unmonitored <- unmonitored_hydrology_annual %>%
  select(WS_Name, Flow.acftyr)
flow_monitored <- monitored_loading_annual %>%
  select(WS_Name, Flow.acftyr)
flow <- rbind(flow_unmonitored, flow_monitored)

flow_tribs <- flow %>%
  summarise(Flow.acftyr = sum(Flow.acftyr)) %>%
  mutate(Source = "Tributaries")

flow_gw <- gw_loading_annual %>%
  summarise(Flow.acftyr = sum(Flow.acftyr)) %>%
  mutate(Source = "Groundwater")

flow_precip <- precipevap_hydrology_monthly %>%
  summarise(Flow.acftyr = sum(precip.acftmo)) %>%
  mutate(Source = "Precipitation")

flow_evap <- precipevap_hydrology_monthly %>%
  summarise(Flow.acftyr = -sum(et.acftmo)) %>%
  mutate(Source = "Evaporation")

flow_jordan <- jordan_loading_annual %>%
  summarise(Flow.acftyr = -Flow.acftyr) %>%
  mutate(Source = "Jordan River")
  
flow_total <- rbind(flow_tribs, flow_gw, flow_precip, flow_evap, flow_jordan)

flow_total <- flow_total %>%
  mutate(Flow.percent = case_when(Flow.acftyr > 0 ~ Flow.acftyr/sum(Flow.acftyr[which(Flow.acftyr>0)])*100, 
                                  Flow.acftyr < 0 ~ Flow.acftyr/sum(Flow.acftyr[which(Flow.acftyr<0)])*100)) 
flow_total$Flow.percent <- round(flow_total$Flow.percent, digits = 2)

flow_balance <- data.frame(Flow.acftyr = sum(flow_total$Flow.acftyr), 
                           Source = "Balance", 
                           Flow.percent = sum(flow_total$Flow.acftyr)/
                             sum(flow_total$Flow.acftyr[flow_total$Flow.acftyr > 0])*100)
flow_total <- rbind(flow_total, flow_balance)
flow_total$Source <- factor(flow_total$Source, 
         levels = c("Tributaries", "Precipitation", "Groundwater",
                    "Jordan River", "Evaporation", "Balance"))
flow_total$Flow.percent <- paste(flow_total$Flow.percent, "%")  
flow_total$Flow.percent[flow_total$Source == "Balance"] <- "" 

```

## Visualization
### Loading maps
```{r}
# unmonitored only
ggplot(subset(wshds_loading, Monitored_ == "NO")) +
  geom_sf(aes(fill = load.TN.tonyr)) +
  geom_sf(data = subset(wshds_loading, Monitored_ == "YES"), fill = "gray") +
  scale_fill_viridis_c(option = "magma", direction = -1, begin = 0.4) +
  scale_color_manual(values = c("lightgray", "black")) +
  labs(fill = "TN load (metric ton/yr)", color = "Monitored") +
  theme(legend.position = "top")
#ggsave(file = "./Code/Output/TNloadmap_unmonitored.jpg", width = 5, height = 6)

ggplot(subset(wshds_loading, Monitored_ == "NO")) +
  geom_sf(aes(fill = load.TP.tonyr)) +
  geom_sf(data = subset(wshds_loading, Monitored_ == "YES"), fill = "gray") +
  scale_fill_viridis_c(option = "magma", direction = -1, begin = 0.4) +
  scale_color_manual(values = c("lightgray", "black")) +
  labs(fill = "TP load (metric ton/yr)", color = "Monitored") +
  theme(legend.position = "top")
#ggsave(file = "./Code/Output/TPloadmap_unmonitored.jpg", width = 5, height = 6)

ggplot(subset(wshds_loading, Monitored_ == "NO")) +
  geom_sf(aes(fill = Flow.acftyr)) +
  geom_sf(data = subset(wshds_loading, Monitored_ == "YES"), fill = "gray") +
  scale_fill_viridis_c(option = "magma", direction = -1, begin = 0.4) +
  scale_color_manual(values = c("lightgray", "black")) +
  labs(fill = "Inflow (ac*ft/yr)") +
  theme(legend.position = "top")
ggsave(file = "./Code/Output/inflowmap_unmonitored.jpg", width = 5, height = 6)


```


```{r}
# monitored and unmonitored
ggplot(wshds_loading) +
  geom_sf(aes(fill = load.TN.tonyr, color = Monitored_)) +
  #geom_sf_text(data = subset(wshds_loading, Monitored_ == "YES"), aes(label = WS_Name)) +
  #  ggrepel::geom_label_repel(
  #   data = subset(wshds_loading, Monitored_ == "YES"),
  #   aes(label = WS_Name, geometry = geometry),
  #   stat = "sf_coordinates",
  #   min.segment.length = 0
  # ) +
  scale_fill_viridis_c(option = "magma", direction = -1, begin = 0.4) +
  scale_color_manual(values = c("lightgray", "black")) +
  labs(fill = "TN load (metric ton/yr)", color = "Monitored") +
  theme(legend.position = "top")
#ggsave(file = "./Code/Output/map_TNload.jpg", width = 5, height = 6)

ggplot(wshds_loading) +
  geom_sf(aes(fill = load.TDN.tonyr, color = Monitored_)) +
  scale_fill_viridis_c(option = "magma", direction = -1, begin = 0.4) +
  scale_color_manual(values = c("lightgray", "black")) +
  labs(fill = "TDN load (metric ton/yr)", color = "Monitored") +
  theme(legend.position = "top")

ggplot(wshds_loading) +
  geom_sf(aes(fill = load.TP.tonyr, color = Monitored_)) +
  scale_fill_viridis_c(option = "magma", direction = -1, begin = 0.4) +
  scale_color_manual(values = c("lightgray", "black")) +
  labs(fill = "TP load (metric ton/yr)", color = "Monitored") +
  theme(legend.position = "top")
#ggsave(file = "./Code/Output/map_TPload.jpg", width = 5, height = 6)

ggplot(wshds_loading) +
  geom_sf(aes(fill = load.TDP.tonyr, color = Monitored_)) +
  scale_fill_viridis_c(option = "magma", direction = -1, begin = 0.4) +
  scale_color_manual(values = c("lightgray", "black")) +
  labs(fill = "TDP load (metric ton/yr)", color = "Monitored") +
  theme(legend.position = "top")

ggplot(wshds_loading) +
  geom_sf(aes(fill = load.TOC.tonyr, color = Monitored_)) +
  scale_fill_viridis_c(option = "magma", direction = -1, begin = 0.4) +
  scale_color_manual(values = c("lightgray", "black")) +
  labs(fill = "TOC load (metric ton/yr)", color = "Monitored") +
  theme(legend.position = "top")
#ggsave(file = "./Code/Output/map_TOCload.jpg", width = 5, height = 6)

ggplot(wshds_loading) +
  geom_sf(aes(fill = load.DOC.tonyr, color = Monitored_)) +
  scale_fill_viridis_c(option = "magma", direction = -1, begin = 0.4) +
  scale_color_manual(values = c("lightgray", "black")) +
  labs(fill = "DOC load (metric ton/yr)", color = "Monitored") +
  theme(legend.position = "top")

ggplot(wshds_loading) +
  geom_sf(aes(fill = Flow.acftyr, color = Monitored_)) +
  scale_fill_viridis_c(option = "magma", direction = -1, begin = 0.4) +
  scale_color_manual(values = c("lightgray", "black")) +
  labs(fill = "Inflow (ac*ft/yr)", color = "Monitored") +
  theme(legend.position = "top")
#ggsave(file = "./Code/Output/map_hydrology.jpg", width = 5, height = 6)

```

### Monthly time series
```{r}
ggplot(loading_AllWatersheds, aes(x = Month, y = load.TN.tonmo, color = OrganizationIdentifier)) +
  geom_point(alpha = 0.7, size = 2) +
  facet_wrap(vars(WS_Name), ncol = 3) +
  scale_y_log10() +
  scale_x_continuous(n.breaks = 12) +
  labs(y = "TN load (ton/mo)", color = "Organization") +
  scale_color_viridis_d(option = "magma", begin = 0.2, end = 0.7, direction = -1) +
  theme(legend.position = "top")

ggplot(monitored_loading_monthly, aes(x = Month, y = load.TN.tonmo, color = WS_Type)) +
  geom_line() +
  #scale_y_log10() +
  scale_x_continuous(breaks = sequence(1:12)) +
  facet_wrap(vars(WS_Name), ncol = 4) +
  labs(y = "TN load (metric ton/mo)", color = "") +
  scale_color_viridis_d(option = "magma", begin = 0.2, end = 0.7, direction = -1) +
  theme(legend.position = "top")

ggplot(monitored_loading_monthly, aes(x = Month, y = load.TDN.tonmo, color = WS_Type)) +
  geom_line() +
  scale_y_log10() +
  scale_x_continuous(breaks = sequence(1:12)) +
  facet_wrap(vars(WS_Name), ncol = 4) +
  labs(y = "TDN load (metric ton/mo)", color = "") +
  scale_color_viridis_d(option = "magma", begin = 0.2, end = 0.7, direction = -1) +
  theme(legend.position = "top")

ggplot(monitored_loading_monthly, aes(x = Month, y = load.TP.tonmo, color = WS_Type)) +
  geom_line() +
  #scale_y_log10() +
  scale_x_continuous(breaks = sequence(1:12)) +
  facet_wrap(vars(WS_Name), ncol = 4) +
  labs(y = "TP load (metric ton/mo)", color = "") +
  scale_color_viridis_d(option = "magma", begin = 0.2, end = 0.7, direction = -1) +
  theme(legend.position = "top")

ggplot(monitored_loading_monthly, aes(x = Month, y = load.TDP.tonmo, color = WS_Type)) +
  geom_line() +
  scale_y_log10() +
  scale_x_continuous(breaks = sequence(1:12)) +
  facet_wrap(vars(WS_Name), ncol = 4) +
  labs(y = "TDP load (metric ton/mo)", color = "") +
  scale_color_viridis_d(option = "magma", begin = 0.2, end = 0.7, direction = -1) +
  theme(legend.position = "top")

ggplot(monitored_loading_monthly, aes(x = Month, y = load.TOC.tonmo, color = WS_Type)) +
  geom_line() +
  scale_y_log10() +
  scale_x_continuous(breaks = sequence(1:12)) +
  facet_wrap(vars(WS_Name), ncol = 4) +
  labs(y = "TOC load (metric ton/mo)", color = "") +
  scale_color_viridis_d(option = "magma", begin = 0.2, end = 0.7, direction = -1) +
  theme(legend.position = "top")

ggplot(monitored_loading_monthly, aes(x = Month, y = load.DOC.tonmo, color = WS_Type)) +
  geom_line() +
  scale_y_log10() +
  scale_x_continuous(breaks = sequence(1:12)) +
  facet_wrap(vars(WS_Name), ncol = 4) +
  labs(y = "DOC load (metric ton/mo)", color = "") +
  scale_color_viridis_d(option = "magma", begin = 0.2, end = 0.7, direction = -1) +
  theme(legend.position = "top")

ggplot(monitored_loading_monthly, aes(x = Month, y = Flow.acftmo, color = WS_Type)) +
  geom_line() +
  scale_y_log10() +
  scale_x_continuous(breaks = sequence(1:12)) +
  facet_wrap(vars(WS_Name), ncol = 4, labeller = label_wrap_gen()) +
  labs(y = "Inflow (ac*ft/mo)", color = "") +
  scale_color_viridis_d(option = "magma", begin = 0.2, end = 0.7, direction = -1) +
  theme(legend.position = "top")
# ggsave("./Code/Output/hydrology_monitored_monthly.jpg",
#        height = 6, width = 7)

ggplot(monitored_loading_monthly_total, aes(x = Month, y = Flow.acftmo)) +
  geom_line() +
  geom_line(data = monitored_loading_monthly, color = "gray",
            aes(x = Month, y = Flow.acftmo, group = WS_Name)) +
  #scale_y_log10() +
  scale_x_continuous(breaks = sequence(1:12)) +
  labs(y = "Inflow (ac*ft/mo)", color = "") +
  scale_color_viridis_d(option = "magma", begin = 0.2, end = 0.7, direction = -1) +
  theme(legend.position = "top")
# ggsave("./Code/Output/hydrology_monitored_total_monthly.jpg",
#        height = 4, width = 5)

ggplot(unmonitored_hydrology_monthly, aes(x = Month, y = Flow.acftmo)) +
  geom_line() +
  scale_y_log10() +
  scale_x_continuous(breaks = sequence(1:12)) +
  facet_wrap(vars(WS_Name), ncol = 6, labeller = label_wrap_gen()) +
  labs(y = "Inflow (ac*ft/mo)")
# ggsave("./Code/Output/hydrology_unmonitored_monthly.jpg", 
#        height = 9, width = 9)

ggplot(unmonitored_hydrology_monthly_total, aes(x = Month, y = Flow.acftmo)) +
  geom_line() +
  geom_line(data = unmonitored_hydrology_monthly, color = "gray",
            aes(x = Month, y = Flow.acftmo, group = WS_Name)) +
  # scale_y_log10() +
  scale_x_continuous(breaks = sequence(1:12)) +
  labs(y = "Inflow (ac*ft/mo)", color = "") +
  scale_color_viridis_d(option = "magma", begin = 0.2, end = 0.7, direction = -1) +
  theme(legend.position = "top")
# ggsave("./Code/Output/hydrology_unmonitored_total_monthly.jpg", 
#        height = 4, width = 5)

ggplot(jordan_loading_monthly, aes(x = Month, y = Flow.acftmo)) +
  geom_line() +
  # scale_y_log10() +
  scale_x_continuous(breaks = sequence(1:12)) +
  labs(y = "Outflow (ac*ft/mo)") +
  theme(legend.position = "top")
#ggsave(file = "./Code/Output/jordan_outflow_monthly.jpg", width = 4, height = 3)

  
```

### Annual loads
```{r}
# hydrology
ggplot(flow_total, aes(x = Source, y = Flow.acftyr, fill = Source)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = Flow.percent), 
            vjust = ifelse(flow_total$Flow.acftyr < 0, 1.2, -0.2)) +
  labs(x = "", y = expression("Hydrologic Inflow or Outflow (ac*ft"^3*"/yr)")) +
  scale_fill_manual(values = c("#fc9d6f", "#f27162", "#db4a69",
                               "#8a2880", "#62197d", "gray")) +
  theme(legend.position = "none")
#ggsave(file = "./Code/Output/hydrologyload_total_annual.jpg", width = 6, height = 4)

# nutrients, monitored watersheds
ggplot(monitored_loading_annual, aes(x = WS_Name, y = load.TN.tonyr, fill = WS_Type)) +
  geom_bar(stat = "identity", alpha = 0.8) +
  scale_fill_viridis_d(option = "magma", begin = 0.2, end = 0.7, direction = -1) +
  labs(x = "", y = "TN load (metric tons/yr)", fill = "") +
  theme(legend.position = "top", 
        axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave(file = "./Code/Output/load_TN_monitored_total_annual.jpg", width = 6, height = 5)

ggplot(monitored_loading_annual, aes(x = WS_Name, y = load.TP.tonyr, fill = WS_Type)) +
  geom_bar(stat = "identity", alpha = 0.8) +
  scale_fill_viridis_d(option = "magma", begin = 0.2, end = 0.7, direction = -1) +
  labs(x = "", y = "TP load (metric tons/yr)", fill = "") +
  theme(legend.position = "top", 
        axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave(file = "./Code/Output/load_TP_monitored_total_annual.jpg", width = 6, height = 5)

ggplot(monitored_loading_annual, aes(x = WS_Name, y = load.TOC.tonyr, fill = WS_Type)) +
  geom_bar(stat = "identity", alpha = 0.8) +
  scale_fill_viridis_d(option = "magma", begin = 0.2, end = 0.7, direction = -1) +
  labs(x = "", y = "TOC load (metric tons/yr)", fill = "") +
  theme(legend.position = "top", 
        axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave(file = "./Code/Output/load_TOC_monitored_total_annual.jpg", width = 6, height = 5)

# nutrients, all sources
ggplot(loading_annual_summary, aes(x = WS_Type, y = load.TN.tonyr, fill = WS_Type)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("#b5367a", "#db4a69", "#f27162", "#fc9d6f", "#fecc90", "#3b1165")) +
  geom_text(aes(label = TN.percent), 
            vjust = ifelse(loading_annual_summary$load.TN.tonyr < 0, 1.2, -0.2)) +
  ylim(-200, 1500) +
  labs(x = "", y = "TN load (metric tons/yr)", fill = "") +
  theme(legend.position = "top", 
        axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave(file = "./Code/Output/load_TN_total_annual.jpg", width = 6, height = 4)

ggplot(loading_annual_summary, aes(x = WS_Type, y = load.TP.tonyr, fill = WS_Type)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = TP.percent), 
            vjust = ifelse(loading_annual_summary$load.TP.tonyr < 0, 1.2, -0.2)) +
  ylim(-50, 250) +
  scale_fill_manual(values = c("#b5367a", "#db4a69", "#f27162", "#fc9d6f", "#fecc90", "#3b1165")) +
  labs(x = "", y = "TP load (metric tons/yr)", fill = "") +
  theme(legend.position = "top", 
        axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave(file = "./Code/Output/load_TP_total_annual.jpg", width = 6, height = 4)


```


```{r}
```

