---
title: "UtahLake_TributaryData"
author: "Kateri Salk"
date: "11/24/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(viridis)

theme_set(theme_classic())
```

## Details


## Load data
```{r}
trib <- read.csv("./Data/Processed/ul_Tribdata_wqp_processed.csv")
fac <- read.csv("../Data/Processed/ul_Facilitydata_wqp_processed.csv")
wshds <- read_sf("./Data/GIS/ulSubWshdsWGS84.shp")

#siteID <- read.csv("./Data/Processed/LUT.MLID.csv")
```

## Process data

### Tributary data

1. Find rows in dataset with C, N, or P data
2. Clean up rows and columns
3. Use only data from 2015-present
4. Pivot to wide format

```{r}
trib$datetime <- as.POSIXct(trib$datetime)
#unique(trib$CharacteristicName)
trib$ResultMeasureValue <- as.numeric(trib$ResultMeasureValue)

trib_wq <- trib %>%
  filter(CharacteristicName %in% 
           c("Ammonia-nitrogen as N", "Carbon", "Nitrate as N", "Organic carbon",
             "Ammonium", "Carbonate", "Inorganic carbon", "Nitrate", "Nitrogen", 
             "Phosphorus", "Ammonia and ammonium", 
             "Inorganic nitrogen (nitrate and nitrite)", "Nitrite", "Orthophosphate", 
             "Kjeldahl nitrogen", "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)",
             "Organic Nitrogen", "Ammonia-nitrogen", "Phosphate-phosphorus",
             "Total Kjeldahl nitrogen")) %>%
  filter(ResultMeasure.MeasureUnitCode %in% c("ueq/L", "mg/l", "mg/l as N", "<NA>", "mg/l as P")) %>%
  select(MonitoringLocationIdentifier:LongitudeMeasure, ResultMeasureValue, ResultMeasure.MeasureUnitCode) %>%
  mutate(Month = month(datetime), 
         Year = year(datetime)) %>%
  filter(Year >= 2015) %>%
  droplevels() %>%
  filter(!is.na(ResultMeasureValue)) %>%
  select(-SampleDepthValue, -RelativeDepth, -ResultMeasure.MeasureUnitCode) %>%
  unite("Variable", CharacteristicName:ResultSampleFractionText) %>%
  group_by(MonitoringLocationIdentifier, datetime, OrganizationIdentifier,
           OrganizationFormalName, MonitoringLocationName, MonitoringLocationTypeName,
           LatitudeMeasure, LongitudeMeasure, Month, Year, Variable) %>%
  summarise(ResultMeasureValue = mean(ResultMeasureValue, na.rm = TRUE)) %>%
  pivot_wider(names_from = Variable, values_from = ResultMeasureValue)

colnames(trib_wq)[11:26] <- c("NH3.t", "NO23.d", "NO23.t", "DN", "TN", "DOC", 
                              "TOC", "PO4.d", "PO4.t", "NH3.d", "orthoP.t",
                              "NO3.t", "CO3.t", "TKN.d", "NO2.t", "TKN.t")

# some variables represent the same thing. Fill in NAs from other columns.
summary(trib_wq)

# UL_tributarychem <- 
#   separate(UL_tributarychem, col = MonitoringLocationIdentifier, 
#           into = c(NA, 'MonitoringLocationIdentifier'), sep = "-")



```

```{r}
TribSites <- Data.WQP_Trib %>% distinct(MonitoringLocationIdentifier, MonitoringLocationName, MonitoringLocationTypeName, LatitudeMeasure,LongitudeMeasure)

TribSites_as_sf <- st_as_sf(TribSites, coords = c("LongitudeMeasure", "LatitudeMeasure"), crs = 4326, dim = "XY") #CRS = WGS84

FacSites <- Data.WQP_Fac %>% distinct(MonitoringLocationIdentifier, MonitoringLocationName, MonitoringLocationTypeName, LatitudeMeasure,LongitudeMeasure)

FacSites_as_sf <- st_as_sf(FacSites, coords = c("LongitudeMeasure", "LatitudeMeasure"), crs = 4326, dim = "XY") #CRS = WGS84

tribfacsites_intersect <- TribFacSites_as_sf %>%
  st_intersection(wshds)

DmrFac <- read.csv("./Data/Processed/DmrFacilityInfo.csv")

Dmr_Sp <- st_as_sf(DmrFac,coords = c("dec_long", "dec_lat"),crs=4236)

UL_tributaryflow <- trib %>%
  filter(CharacteristicName %in%
           c("Height, gage", "Stream flow, instantaneous", "Stream flow, mean. daily")) %>%
  droplevels()

```